site_name: DASH
site_url: http://dash-project.org/
site_description: Project documentation of DASH
site_author: DASH-Team

repo_url: https://github.com/dash-project/dash/

extra_javascript: 
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - toc:
        permalink: True
    - admonition:
    - extra:

theme: readthedocs

